# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::981302568566:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-vC5S5NJsKU8y
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::981302568566:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-08T13:00:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1511"
  uid: b0dd8032-907c-4920-b691-f6f639754ff8